# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: MuSun Choi
title: Graduate Student
email: moosunny@korea.ac.kr
website: www.github.com/moosunny

# Dark Mode (true/false/never)
darkmode: false


# Additional icon links
additional_links:
- title: Github Link
  icon: fab fa-github
  url: https://www.github.com/moosunny
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/최무선 (2).jpg.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is MuSun Choi. I am an M.S. student in Industrial & Management Engineering at Korea University.   
  My research interest is in Time-Series Analysis, Machine Learning, Graph-Neural Networks, and Semi-Supervised Learning. 
  
  - Methodologies: Machine Learning, Deep Learning, GNN
  - Applications: Battery Swapping Station based two-wheeled vehicles, Allocation Battery Swapping Stataion

content:
  - title: Education
    layout: list
    content:
      - layout: top
        title: Korea University
        # sub_title: 2023 - 2025
        caption: 2023 - 2025
        description: | # this will include new lines to allow paragraphs
          M.S. in Industrial Management Engineering
      - layout: top
        title: Tech University of Korea
        # sub_title: 2017 - 2023
        caption: 2016 - 2022
        description: | # this will include new lines to allow paragraphs
          B.S. in Industrial Management and Administration

  - title: Publications
    layout: list
    content:
      - layout: top
        title: International Journals
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        description: | # this will include new lines to allow paragraphs
          - (Works in Progress) Hyungjoo Cha, Joonghoo Park, Chungmok Lee* and Taesu Cheong*, "An Exact algorithm for Vehicle Routing Problem with Availability Profiles"
          - (Works in Progress) Joonghoo Park, Gwangjong Ko, Hyungjoo Cha and Taesu Cheong*, “Vehicle routing problem with metro based backhauls and MFCs”
          - (Works in Progress) Joonghoo Park, Hyungjoo Cha, San Kwon and Taesu Cheong*, “Temporary medical shelter location-routing problem with manpower allocation in a disaster situation”
          - Seongjin Lee, Joonghoo Park, Seungmin Cha and Donghyun Kim* (2022), “A Regional Economy’s Resistance to the COVID-19 Shock: Sales Revenues of Micro-, Small-, and Medium-Sized Enterprises in South Korea”, International Journal of Disaster Risk Science

  - title: Conferences
    layout: list
    content:
      - layout: top
        title: International Conferences
        # sub_title: Job title
        # caption: Date Range (eg. November 2016 - present)
        # link: Link to company (optional)
        description: | # this will include new lines to allow paragraphs
          - Joonghoo Park, Hyungjoo Cha, San Kwon and Taesu Cheong*, “Temporary medical shelter location-routing problem with manpower allocation in a disaster situation”, 2024 INFORMS Annual Meeting, Nov 2024.
          - Joonghoo Park, Gwangjong Ko and Taesu Cheong*, “Micro-fulfillment center location routing problem with underground logistics system”, 2024 International Conference of Asian Shipping and Logistics, Jun 2024.  

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Samsung Display
        caption: Mar. 2024 - Present
        description: | # this will include new lines to allow paragraphs
          Optimize facility planning by using optimization, Research Assistant @ Korea University
      - layout: top
        title: IITP
        caption: Feb. 2024 - Present
        description: | # this will include new lines to allow paragraphs
          Development of NetZero Building Energy Efficient System through AI-based HVAC system control, Information and Communication Planning and Evaluation Institute, Research Assistant @ Korea University 
      - layout: top
        title: Samsung Electronics
        caption: Nov. 2023 - Feb. 2024
        description: | # this will include new lines to allow paragraphs
          Maximize productivity by changing facility and logistics layouts Model development, Research Assistant @ Korea University
  
  - title: Research Experience
    layout: list
    content:
      - layout: top
        title: Bigdata Analytics & Engineering Lab
        # sub_title: Research Intern
        caption: 2022 - 2023
        # link: Link to company (optional)
        description: | # this will include new lines to allow paragraphs
          Research Intern at Bigdata Analytics & Engineering Lab, Pusan National University
      - layout: top
        title: Regional Development & Planning Lab
        # sub_title: Research Intern
        caption: 2021 - 2022
        # link: Link to company (optional)
        description: | # this will include new lines to allow paragraphs
          Research Intern at Regional Development & Planning Lab, Pusan National University

  - title: Awards & Honors
    layout: list
    content:
      - layout: top
        title: Korea University
        description: | # this will include new lines to allow paragraphs
          Graduate School Mentor-Mentee Program, 2024
      - layout: top
        title: Korea University
        description: | # this will include new lines to allow paragraphs
          Future Talent Scholarship Student, 2023

  - title: Additional Information
    layout: list
    content:
      - layout: top
        title: Programming Languages
        description: | # this will include new lines to allow paragraphs
          - Python
          - JAVA
          - SQL
      - layout: top
        title: Optimization Software
        description: | # this will include new lines to allow paragraphs
          - CPLEX
          - Gurobi
      - layout: top
        title: Military Service
        caption: Apr. 2017 - Jan. 2019
        description: | # this will include new lines to allow paragraphs
          Republic of Korea Air Force

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
